# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16.3
jobs:
  build-lib:
    !!merge <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - lib
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint-lib:
    !!merge <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run lint
  publish:
    !!merge <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: cp ~/repo/README.md ~/repo/lib/README.md
      - run: cp ~/repo/package.json ~/repo/lib/package.json
      - run: cd ~/repo/lib && npm version --no-git-tag-version ${CIRCLE_TAG}
      - run: npm publish ~/repo/lib --access public
workflows:
  version: 2
  test-deploy:
    jobs:
      - build-lib:
          filters:
            tags:
              only: /.*/
      - lint-lib:
          requires:
            - build-lib
          filters:
            tags:
              ignore: /.*/
      - publish:
          requires:
            - build-lib
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
orbs:
  prometheus: prometheus/prometheus@0.11.0
